CXX = g++
CXXFLAGS = -std=c++17 -Wall -Werror

TARGET = loadbalancer
SRCS = main.cpp LoadBalancer.cpp WebServer.cpp
OBJS = $(SRCS:.cpp=.o)

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(TARGET) $(OBJS) log.txt

.PHONY: all clean
